name: social_share
description: Wide variety of sharing options you'll need to share directly to certain well-known apps.
version: 2.4.0
homepage: https://github.com/ShekarMudaliyar/social_share

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.shekarmudaliyar.social_share
        pluginClass: SocialSharePlugin
      ios:
        pluginClass: SocialSharePlugin